spring:
  config:
    location: "kubernetes:,/config/application.yml"

management:
  endpoints:
      web:
        exposure:
          include: "*"
  endpoint:
    restart:
      enabled: true
    refresh:
      enabled: true
    env:
      enabled: true
user:
  first-name: justin
  last-name: bieber

secrets:
  username: lmao
  password: what
