apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: spring-cloud-kubernetes-configuration-watcher
  name: spring-cloud-kubernetes-configuration-watcher

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: config-watch-role
  namespace: default
rules:
  - apiGroups: ["", "extensions", "apps", "discovery.k8s.io"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: demo-app 
    namespace: default
  name: demo-app 
roleRef:
  kind: Role
  name: config-watch-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: spring-cloud-kubernetes-configuration-watcher
    namespace: default

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: spring-cloud-kubernetes-configuration-watcher-deployment
    namespace: default
spec:
  selector:
    matchLabels:
      app: spring-cloud-kubernetes-configuration-watcher
  template:
    metadata:
      labels:
        app: spring-cloud-kubernetes-configuration-watcher
    spec:
      serviceAccountName: spring-cloud-kubernetes-configuration-watcher
      containers:
        - name: spring-cloud-kubernetes-configuration-watcher
          image: springcloud/spring-cloud-kubernetes-configuration-watcher:3.2.0
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8888
              path: /actuator/health/readiness
          livenessProbe:
              httpGet:
                port: 8888
                path: /actuator/health/liveness
          ports:
            - containerPort: 8888
          env:
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_KUBERNETES_CONFIGURATION_WATCHER
              value: DEBUG
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_KUBERNETES_CLIENT_CONFIG_RELOAD
              value: DEBUG
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_KUBERNETES_COMMONS_CONFIG_RELOAD
              value: DEBUG
            - name: SPRING_CLOUD_KUBERNETES_CONFIGURATION_WATCHER_REFRESHDELAY
              value: "120000"
            - name: SPRING_CLOUD_KUBERNETES_RELOAD_NAMESPACES_0
              value: "default"
          
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-cloud-kubernetes-configuration-watcher
  name: spring-cloud-kubernetes-configuration-watcher
spec:
  ports:
    - name: http
      port: 8888
      targetPort: 8888
  selector:
    app: spring-cloud-kubernetes-configuration-watcher
  type: NodePort
