apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  labels:
    spring.cloud.kubernetes.config: "true"
  annotations:
    spring.cloud.kubernetes.configmap.apps: "demo-app"
data:
  application.yml: |
    spring:
      cloud:
        kubernetes:
          config:
            enabled: true
          reload:
            enabled: true
            strategy: refresh
            event: event
    user:
      first-name: austin
      last-name: bieber
    logging:
      level:
        root: DEBUG
